import type { Pandal, Profile, Rating, FriendActivity } from '../types/database.types';

export const INITIAL_USER: Profile = {
  id: 'user_me',
  username: 'himan_b',
  display_name: 'Himan Barman',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  bio: 'Exploring Kolkata Puja pandals one by one • South & North enthusiast',
  created_at: '2026-08-01T10:00:00Z',
};

export const MOCK_FRIENDS: Profile[] = [
  {
    id: 'user_ananya',
    username: 'ananya_r',
    display_name: 'Ananya Roy',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    bio: 'Photographer & Puja hopper. Tracking every pandal in South Kolkata.',
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'user_rahul',
    username: 'rahul_m',
    display_name: 'Rahul Mukherjee',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    bio: 'Traditional Bonedi Bari and North Kolkata pandal fan.',
    created_at: '2026-08-12T10:00:00Z',
  },
  {
    id: 'user_priya',
    username: 'priya_sen',
    display_name: 'Priya Sen',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    bio: 'All-night pandal hopper. Coffee, dhak, and architecture.',
    created_at: '2026-08-15T10:00:00Z',
  },
  {
    id: 'user_sourav',
    username: 'sourav_d',
    display_name: 'Sourav Das',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'Salt Lake & East Kolkata local guide.',
    created_at: '2026-08-18T10:00:00Z',
  },
  {
    id: 'user_debolina',
    username: 'debolina_d',
    display_name: 'Debolina Dutta',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    bio: 'Minimalist idol appreciator • Art curator in Kolkata',
    created_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'user_rittik',
    username: 'rittik_b',
    display_name: 'Rittik Bhattacharya',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
    bio: 'Dhak beats & street food enthusiast.',
    created_at: '2026-08-22T10:00:00Z',
  }
];

export const OTHER_USERS: Profile[] = [
  {
    id: 'user_tanmay',
    username: 'tanmay_k',
    display_name: 'Tanmay Karmakar',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
    bio: 'Lighting design reviewer. Chandannagar fan.',
    created_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'user_swagata',
    username: 'swagata_b',
    display_name: 'Swagata Banerjee',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    bio: 'Bonedi Bari heritage walk organizer.',
    created_at: '2026-08-26T10:00:00Z',
  }
];

export const MOCK_PANDALS: Pandal[] = [
  {
    "id": "bagbazar-sarbojanin",
    "name": "Bagbazar Sarbojanin Durgotsab",
    "slug": "bagbazar-sarbojanin",
    "description": "One of Kolkata's oldest and most iconic sarbojanin (community) Durga Pujas. Founded in 1919, Bagbazar Sarbojanin is renowned for its traditional Daker Saaj (pith decoration) on the idol and its authentic old-world Bengali Puja atmosphere near the Hooghly riverbank.",
    "address": "Near Bagbazar Launch Ghat, Bagbazar, Kolkata, West Bengal 700003",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.5985,
    "longitude": 88.362,
    "image_url": "https://images.unsplash.com/photo-1601056641838-8c1173663673?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "kumartuli-park",
    "name": "Kumartuli Park Durga Puja",
    "slug": "kumartuli-park",
    "description": "Located in the heart of Kolkata's legendary potters' quarter (Kumartuli), this puja is celebrated for its innovative fusion of traditional idol-making craft with contemporary artistic themes.",
    "address": "Banamali Sarkar Street, Kumartuli, Kolkata, West Bengal 700005",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.596,
    "longitude": 88.361,
    "image_url": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "ahiritola-sarbojanin",
    "name": "Ahiritola Sarbojanin Durgotsab",
    "slug": "ahiritola-sarbojanin",
    "description": "A long-standing traditional puja near Bagbazar that balances traditional values with artistic, theme-based decorations and rich cultural programs.",
    "address": "55, B.K. Pal Avenue, Ahiritola, Kolkata, West Bengal 700005",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.5945,
    "longitude": 88.3635,
    "image_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "college-square",
    "name": "College Square Durga Puja",
    "slug": "college-square",
    "description": "Iconic Durga Puja celebrated beside the historic College Square tank. The reflection of the brilliantly illuminated pandal on the water creates one of the most photographed scenes of Kolkata Puja.",
    "address": "College Square, College Street, Kolkata, West Bengal 700073",
    "zone": "Central Kolkata",
    "city": "Kolkata",
    "latitude": 22.5766,
    "longitude": 88.3632,
    "image_url": "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "hatibagan-sarbojanin",
    "name": "Hatibagan Sarbojanin Durgotsab",
    "slug": "hatibagan-sarbojanin",
    "description": "A landmark puja in the heart of North Kolkata, known for balancing traditional roots with impressive large-scale themes.",
    "address": "Hatibagan, Bidhan Sarani, Kolkata, West Bengal 700006",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.587,
    "longitude": 88.369,
    "image_url": "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "manicktala-chaltabagan",
    "name": "Manicktala Chaltabagan Lohapatty",
    "slug": "manicktala-chaltabagan",
    "description": "A legendary puja started in 1943, widely acclaimed for its unique artistic setups and consistently award-winning decorations. Known for creative blends of nature and heritage.",
    "address": "Chaltabagan, Manicktala, Kolkata, West Bengal 700054",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.583,
    "longitude": 88.377,
    "image_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "kashi-bose-lane",
    "name": "Kashi Bose Lane Sarbojanin Durgotsab",
    "slug": "kashi-bose-lane",
    "description": "Renowned for its creative and socially relevant themes that often carry strong messages about contemporary social issues.",
    "address": "Kashi Bose Lane, Nalin Sarkar Street, Shyambazar, Kolkata, West Bengal 700004",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.59,
    "longitude": 88.366,
    "image_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "sikdar-bagan",
    "name": "Sikdar Bagan Sadharan Durga Puja",
    "slug": "sikdar-bagan",
    "description": "Celebrated for its authentic, traditional atmosphere, representing the quintessential old Kolkata neighbourhood puja experience.",
    "address": "Sikdar Bagan Street, Shyambazar, Kolkata, West Bengal 700004",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.588,
    "longitude": 88.368,
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "tala-prattay",
    "name": "Tala Prattay",
    "slug": "tala-prattay",
    "description": "Widely celebrated for its avant-garde and highly sophisticated artistic themes that push creative boundaries.",
    "address": "Tala, Kolkata, West Bengal 700037",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.589,
    "longitude": 88.375,
    "image_url": "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "santosh-mitra-square",
    "name": "Santosh Mitra Square (Lebutala Park)",
    "slug": "santosh-mitra-square",
    "description": "One of the most famous and high-budget pandals in Kolkata, Santosh Mitra Square is known for its grand, intricate theme installations that frequently feature massive recreations of famous monuments and architectural wonders.",
    "address": "Natabar Dutta Row, Lebutala, Bowbazar, Kolkata, West Bengal 700014",
    "zone": "Central Kolkata",
    "city": "Kolkata",
    "latitude": 22.5659,
    "longitude": 88.3656,
    "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "mohammad-ali-park",
    "name": "Mohammad Ali Park Durga Puja",
    "slug": "mohammad-ali-park",
    "description": "A prestigious and historic Durga Puja venue on Chittaranjan Avenue, known since 1969 for its creative architectural themes and elaborate decorations.",
    "address": "Mohammad Ali Park, Chittaranjan Avenue, College Square, Kolkata, West Bengal 700073",
    "zone": "Central Kolkata",
    "city": "Kolkata",
    "latitude": 22.5772,
    "longitude": 88.3607,
    "image_url": "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "deshapriya-park",
    "name": "Deshapriya Park Durga Puja",
    "slug": "deshapriya-park",
    "description": "One of South Kolkata's most famous pujas, known for its massive scale and ambitious, trend-setting themed installations that attract visitors from across the city.",
    "address": "34A, Manoharpukur Road, Deshapriya Park, Kolkata, West Bengal 700029",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.5183,
    "longitude": 88.3537,
    "image_url": "https://images.unsplash.com/photo-1601056641838-8c1173663673?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "ekdalia-evergreen",
    "name": "Ekdalia Evergreen Club",
    "slug": "ekdalia-evergreen",
    "description": "Famous for grand recreations of famous Indian temples and magnificent lighting. Ekdalia Evergreen is a perennial fixture of South Kolkata's puja circuit.",
    "address": "15, Ekdalia Road, Ballygunge, Kolkata, West Bengal 700019",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.5209,
    "longitude": 88.3658,
    "image_url": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "suruchi-sangha",
    "name": "Suruchi Sangha",
    "slug": "suruchi-sangha",
    "description": "One of the most famous theme pujas in Kolkata, Suruchi Sangha is renowned for its culturally authentic themes that highlight the heritage, art, or social landscape of different Indian states and regions.",
    "address": "500 & 505, Block M, New Alipore, Kolkata, West Bengal 700053",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.506,
    "longitude": 88.335,
    "image_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "chetla-agrani",
    "name": "Chetla Agrani Club",
    "slug": "chetla-agrani",
    "description": "A flagship puja in South Kolkata known for its immense grandeur and cutting-edge thematic innovation, often using unique materials and immersive storytelling.",
    "address": "14, Peary Mohan Roy Road, Chetla, Kolkata, West Bengal 700027",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.514,
    "longitude": 88.342,
    "image_url": "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "mudiali-club",
    "name": "Mudiali Club",
    "slug": "mudiali-club",
    "description": "A must-visit puja near Rabindra Sarobar, known for its blend of modern creativity and classic artistic standards.",
    "address": "3, Rajani Sen Road, Kalighat, Kolkata, West Bengal 700026",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.512,
    "longitude": 88.344,
    "image_url": "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "singhi-park",
    "name": "Singhi Park Sarbojanin Durgotsab",
    "slug": "singhi-park",
    "description": "One of the oldest and most respected pujas in South Kolkata, celebrated for its traditional grandeur and impressive idol artistry.",
    "address": "5, Ramani Chatterjee Road, Ballygunge, Kolkata, West Bengal 700029",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.522,
    "longitude": 88.362,
    "image_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "tridhara-sammilani",
    "name": "Tridhara Sammilani",
    "slug": "tridhara-sammilani",
    "description": "Known for sophisticated, artistic pandals and unique contemporary concepts in the heart of South Kolkata.",
    "address": "107, Manoharpukur Road, Kalighat, Kolkata, West Bengal 700029",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.5196,
    "longitude": 88.3556,
    "image_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "ballygunge-cultural",
    "name": "Ballygunge Cultural Association",
    "slug": "ballygunge-cultural",
    "description": "A staple of South Kolkata Pujo with a reputation for consistent high-quality decor and thematic presentations.",
    "address": "20, Lake View Road, Lake Terrace, Kalighat, Kolkata, West Bengal 700029",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.517,
    "longitude": 88.353,
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "samaj-sebi-sangha",
    "name": "Samaj Sebi Sangha",
    "slug": "samaj-sebi-sangha",
    "description": "Highly regarded for its aesthetic and often socially conscious themes.",
    "address": "24A, Lake View Road, Kolkata, West Bengal 700029",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.5165,
    "longitude": 88.3525,
    "image_url": "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "jodhpur-park",
    "name": "Jodhpur Park Saradiya Utsab",
    "slug": "jodhpur-park",
    "description": "Extremely popular for its innovative pandal structures and massive crowds. A major crowd-puller in South Kolkata.",
    "address": "1/D, Jodhpur Park, Kolkata, West Bengal 700068",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.505,
    "longitude": 88.359,
    "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "hindustan-park",
    "name": "Hindustan Park Sarbojanin Durgotsab",
    "slug": "hindustan-park",
    "description": "A prominent community puja near Gol Park, opposite Basanti Devi College. Known for its mix of tradition and creative themes.",
    "address": "51/1, Hindustan Park, Gol Park, Dhakuria, Kolkata, West Bengal 700029",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.5145,
    "longitude": 88.363,
    "image_url": "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "badamtala-ashar-sangha",
    "name": "Badamtala Ashar Sangha",
    "slug": "badamtala-ashar-sangha",
    "description": "Celebrated for unique, thought-provoking themes and creative excellence near Kalighat.",
    "address": "Badamtala, Kalighat, Kolkata, West Bengal 700026",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.5175,
    "longitude": 88.347,
    "image_url": "https://images.unsplash.com/photo-1601056641838-8c1173663673?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "bhawanipore-75-pally",
    "name": "Bhawanipore 75 Pally",
    "slug": "bhawanipore-75-pally",
    "description": "A very prominent and prestigious community puja in Bhawanipore, famous for its intricate pandal designs and cultural/social narrative themes.",
    "address": "Bhawanipore, Kolkata, West Bengal 700025",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.525,
    "longitude": 88.347,
    "image_url": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "66-pally",
    "name": "66 Pally Durga Puja",
    "slug": "66-pally",
    "description": "A well-known community puja in the Bhawanipore area, often visited on the same circuit as 75 Pally.",
    "address": "66 Pally, Bhawanipore, Kolkata, West Bengal 700025",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.524,
    "longitude": 88.346,
    "image_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "naktala-udayan-sangha",
    "name": "Naktala Udayan Sangha",
    "slug": "naktala-udayan-sangha",
    "description": "One of the most prominent pujas in South Kolkata, consistently recognized for its socially reflective and highly artistic themes.",
    "address": "1/250, Krisanu Dey Sarani, Naktala, Garia, Kolkata, West Bengal 700047",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.468,
    "longitude": 88.372,
    "image_url": "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "bosepukur-sitala-mandir",
    "name": "Bosepukur Sitala Mandir",
    "slug": "bosepukur-sitala-mandir",
    "description": "A pioneer in theme-based pujas in the Kasba region, consistently ranked among the top must-visit spots in South Kolkata.",
    "address": "1/27, Bose Pukur Road, Tal Bagan, Bosepukur, Kasba, Kolkata, West Bengal 700042",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.494,
    "longitude": 88.378,
    "image_url": "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "santoshpur-lake-pally",
    "name": "Santoshpur Lake Pally",
    "slug": "santoshpur-lake-pally",
    "description": "One of the most famous pujas in the Santoshpur area, known for elaborate themes and artistic excellence.",
    "address": "Lake Terrace, Lake West Road, Santoshpur, Kolkata, West Bengal 700075",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.485,
    "longitude": 88.384,
    "image_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "rajdanga-naba-uday",
    "name": "Rajdanga Naba Uday Sangha",
    "slug": "rajdanga-naba-uday",
    "description": "Highly regarded for its grand scale and high-production thematic displays in the Kasba/Rajdanga area.",
    "address": "Rajdanga Main Road, Rajdanga, Kasba, Kolkata, West Bengal 700107",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.499,
    "longitude": 88.383,
    "image_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "sreebhumi-sporting-club",
    "name": "Sreebhumi Sporting Club",
    "slug": "sreebhumi-sporting-club",
    "description": "Widely considered one of the biggest crowd-pullers in Kolkata. Famous for massive, opulent themes — often replicating iconic palaces or temples from across India — with glittering light displays that draw millions.",
    "address": "198, Canal Street, Sreebhumi, Lake Town, South Dumdum, Kolkata, West Bengal 700048",
    "zone": "Salt Lake & East",
    "city": "Kolkata",
    "latitude": 22.6003,
    "longitude": 88.4025,
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "lake-town-adhibasi-brinda",
    "name": "Lake Town Adhibasi Brinda",
    "slug": "lake-town-adhibasi-brinda",
    "description": "Known for focusing on themes related to social awareness, rural life, and cultural heritage, offering a more grounded and meaningful festive atmosphere.",
    "address": "Lake Town, South Dumdum, Kolkata, West Bengal 700048",
    "zone": "Salt Lake & East",
    "city": "Kolkata",
    "latitude": 22.598,
    "longitude": 88.401,
    "image_url": "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "dum-dum-park-tarun-sangha",
    "name": "Dum Dum Park Tarun Sangha",
    "slug": "dum-dum-park-tarun-sangha",
    "description": "A perennial crowd-puller known for its creative, vibrant themes and artistic displays.",
    "address": "Dum Dum Park, Dum Dum, Kolkata, West Bengal 700055",
    "zone": "Salt Lake & East",
    "city": "Kolkata",
    "latitude": 22.61,
    "longitude": 88.395,
    "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "dum-dum-park-bharat-chakra",
    "name": "Dum Dum Park Bharat Chakra",
    "slug": "dum-dum-park-bharat-chakra",
    "description": "Highly regarded for its unique and innovative pandal concepts in the Dum Dum area.",
    "address": "Dum Dum Park, Dum Dum, Kolkata, West Bengal 700055",
    "zone": "Salt Lake & East",
    "city": "Kolkata",
    "latitude": 22.611,
    "longitude": 88.394,
    "image_url": "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "salt-lake-fd-block",
    "name": "FD Block Salt Lake Durga Puja",
    "slug": "salt-lake-fd-block",
    "description": "One of the most famous and highly-rated pandals in Salt Lake, known for elaborate and creative thematic displays in a family-friendly environment.",
    "address": "FD Block, Sector III, Salt Lake City, Kolkata, West Bengal 700106",
    "zone": "Salt Lake & East",
    "city": "Kolkata",
    "latitude": 22.575,
    "longitude": 88.415,
    "image_url": "https://images.unsplash.com/photo-1601056641838-8c1173663673?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "salt-lake-ae-block",
    "name": "AE Block Salt Lake Durga Puja",
    "slug": "salt-lake-ae-block",
    "description": "A well-known block puja in Salt Lake Sector II, praised for being family-friendly and well-managed.",
    "address": "AE Block, Sector II, Salt Lake City, Kolkata, West Bengal 700064",
    "zone": "Salt Lake & East",
    "city": "Kolkata",
    "latitude": 22.578,
    "longitude": 88.41,
    "image_url": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "barisha-club",
    "name": "Barisha Club Durga Puja",
    "slug": "barisha-club",
    "description": "One of the most iconic pujas in the Behala-Barisha region, consistently praised for its socially conscious and highly innovative themes.",
    "address": "5 & 8, Santosh Roy Road, Sakherbazar, Barisha, Kolkata, West Bengal 700008",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.45,
    "longitude": 88.313,
    "image_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "behala-nutan-dal",
    "name": "Behala Nutan Dal",
    "slug": "behala-nutan-dal",
    "description": "Known for ambitious, globally inspired themes. Considered a must-visit for those who appreciate thoughtful and artistic pandal designs.",
    "address": "Near Behala 14 No. Bus Stand, Behala, Kolkata, West Bengal 700034",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.465,
    "longitude": 88.312,
    "image_url": "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "haridevpur-41-pally",
    "name": "Haridevpur 41 Pally",
    "slug": "haridevpur-41-pally",
    "description": "One of the most popular and non-negotiable stops in South Kolkata for pandal hoppers. Famous for grand-scale thematic presentations and meticulous execution.",
    "address": "41 Pally, Haridevpur, Kolkata, West Bengal 700082",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.455,
    "longitude": 88.33,
    "image_url": "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "santoshpur-trikon-park",
    "name": "Santoshpur Trikon Park",
    "slug": "santoshpur-trikon-park",
    "description": "A well-known community puja in the Santoshpur area that attracts large crowds.",
    "address": "Trikon Park, Santoshpur, Kolkata, West Bengal 700075",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.487,
    "longitude": 88.387,
    "image_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "alipore-sarbajanin",
    "name": "Alipore Sarbajanin Durgotsab",
    "slug": "alipore-sarbajanin",
    "description": "A landmark puja in the Alipore area, recognized for its longstanding tradition and elegant celebrations.",
    "address": "Alipore Road, Alipore, Kolkata, West Bengal 700027",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.529,
    "longitude": 88.333,
    "image_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "new-town-sarbojanin",
    "name": "New Town Sarbojanin Durgotsav",
    "slug": "new-town-sarbojanin",
    "description": "The flagship Durga Puja celebration for the New Town township near the Clock Tower. Features contemporary themes and modern organization.",
    "address": "Near Clock Tower, City Square, New Town, Rajarhat, Kolkata, West Bengal 700156",
    "zone": "Salt Lake & East",
    "city": "Kolkata",
    "latitude": 22.587,
    "longitude": 88.462,
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "belgachia-sadharan",
    "name": "Belgachia Sadharan Durgotsab",
    "slug": "belgachia-sadharan",
    "description": "A well-known community puja in the Belgachia area of North Kolkata.",
    "address": "Belgachia, Kolkata, West Bengal 700037",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.59,
    "longitude": 88.38,
    "image_url": "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "cossipore-shakti-sangha",
    "name": "Cossipore Shakti Sangha",
    "slug": "cossipore-shakti-sangha",
    "description": "A recognized community puja in the Cossipore area of North Kolkata.",
    "address": "Cossipore, Kolkata, West Bengal 700002",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.602,
    "longitude": 88.368,
    "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "arjunpur-amra-sabai",
    "name": "Arjunpur Amra Sabai",
    "slug": "arjunpur-amra-sabai",
    "description": "A popular puja destination in the Dum Dum locality drawing significant visitors for its themes.",
    "address": "Arjunpur, Dum Dum, Kolkata, West Bengal 700055",
    "zone": "Salt Lake & East",
    "city": "Kolkata",
    "latitude": 22.613,
    "longitude": 88.393,
    "image_url": "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "bhabanipore-abasar",
    "name": "Bhabanipore Abasar",
    "slug": "bhabanipore-abasar",
    "description": "Often creates dreamy, imaginative themes that feel more like immersive art installations than traditional pandals.",
    "address": "Bhawanipore, Kolkata, West Bengal 700025",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.526,
    "longitude": 88.348,
    "image_url": "https://images.unsplash.com/photo-1601056641838-8c1173663673?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "nalin-sarkar-street",
    "name": "Nalin Sarkar Street Sarbojanin",
    "slug": "nalin-sarkar-street",
    "description": "A breath of fresh air in North Kolkata, known for its creative blend of nature and heritage, and idols crafted with unique pottery styles.",
    "address": "Nalin Sarkar Street, Shyambazar, Kolkata, West Bengal 700004",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.589,
    "longitude": 88.367,
    "image_url": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "sovabazar-rajbari",
    "name": "Sovabazar Rajbari Durga Puja",
    "slug": "sovabazar-rajbari",
    "description": "One of Kolkata's most historic and famous Bonedi Bari pujas, founded by Raja Nabakrishna Deb in 1757 following the Battle of Plassey. Known for once hosting British dignitaries like Lord Clive and Warren Hastings.",
    "address": "36, Raja Nabakrishna Street, Sovabazar, Kolkata, West Bengal 700005",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.593,
    "longitude": 88.361,
    "image_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "khelat-chandra-ghosh-bari",
    "name": "Khelat Chandra Ghosh Bari (Pathuriaghata)",
    "slug": "khelat-chandra-ghosh-bari",
    "description": "Established around 1855 by Babu Khelat Chandra Ghosh, a noted philanthropist. The mansion (Khelat Bhawan) is a Grade I heritage structure, famous for its long majestic thakur dalan, Belgian chandeliers, and deep association with Indian classical music.",
    "address": "Pathuriaghata, Kolkata, West Bengal 700006",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.586,
    "longitude": 88.364,
    "image_url": "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "laha-bari",
    "name": "Laha Bari Durga Puja",
    "slug": "laha-bari",
    "description": "Initiated by Bhagabati Charan Laha over two centuries ago. Known for its unique idol where the Goddess is traditionally not depicted in the standard Mahishasuramardini form. The puja rotates between different family branches.",
    "address": "Pathuriaghata, Kolkata, West Bengal 700006",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.5855,
    "longitude": 88.365,
    "image_url": "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "sabarna-roy-choudhury",
    "name": "Sabarna Roy Choudhury Aatchala Bari",
    "slug": "sabarna-roy-choudhury",
    "description": "Widely regarded as the oldest Durga Puja in the Kolkata region, initiated in 1610 by Lakshmikanta Gangopadhyay (Roy Choudhury). One of the first Saparivara Durga Pujas. Today 8 separate pujas are held by family branches — 6 in Barisha, 1 in Birati, 1 in Nimta.",
    "address": "67/3, Diamond Harbour Road, Barisha, Kolkata, West Bengal 700008",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.448,
    "longitude": 88.31,
    "image_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "jorasanko-daw-bari",
    "name": "Jorasanko Daw Bari Durga Puja",
    "slug": "jorasanko-daw-bari",
    "description": "Famous for its 'Bandookwala' (gun-toting) family tradition, traditional Daker Saaj (pith decoration), and the ceremonial cannon fire during Sandhi Puja.",
    "address": "Jorasanko, Kolkata, West Bengal 700007",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.585,
    "longitude": 88.359,
    "image_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "darjipara-mitra-bari",
    "name": "Darjipara Mitra Bari Durga Puja",
    "slug": "darjipara-mitra-bari",
    "description": "A highly traditional puja established in 1807, known for its adherence to strict, ancient rituals.",
    "address": "Darjipara, Kolkata, West Bengal 700006",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.587,
    "longitude": 88.363,
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "thanthania-dutta-bari",
    "name": "Thanthania Dutta Bari Durga Puja",
    "slug": "thanthania-dutta-bari",
    "description": "Celebrated since 1855, this family puja is cherished for its intimate, spiritual atmosphere.",
    "address": "Thanthania, Kolkata, West Bengal 700004",
    "zone": "Central Kolkata",
    "city": "Kolkata",
    "latitude": 22.58,
    "longitude": 88.36,
    "image_url": "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "bhukailash-rajbari",
    "name": "Bhukailash Rajbari Durga Puja",
    "slug": "bhukailash-rajbari",
    "description": "Founded by Raja Jaynarayan Ghoshal in the 18th century, set within a historic palace complex in Khidderpore.",
    "address": "Bhukailash, Khidderpore, Kolkata, West Bengal 700023",
    "zone": "Howrah",
    "city": "Kolkata",
    "latitude": 22.533,
    "longitude": 88.325,
    "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "behala-jagat-ram-mukherjee",
    "name": "Behala Jagat Ram Mukherjee Bari",
    "slug": "behala-jagat-ram-mukherjee",
    "description": "Famous for its unique 'Sonar Durga' (Golden Durga) idol.",
    "address": "Behala, Kolkata, West Bengal 700034",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.46,
    "longitude": 88.315,
    "image_url": "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "rani-rashmoni-bari",
    "name": "Rani Rashmoni Bari (Janbazar)",
    "slug": "rani-rashmoni-bari",
    "description": "The ancestral home of Rani Rashmoni, the legendary philanthropist and founder of Dakshineswar Kali Temple. Her family's Durga Puja continues as a significant heritage tradition.",
    "address": "Rani Rashmoni Road, Janbazar, Kolkata, West Bengal 700017",
    "zone": "Central Kolkata",
    "city": "Kolkata",
    "latitude": 22.559,
    "longitude": 88.354,
    "image_url": "https://images.unsplash.com/photo-1601056641838-8c1173663673?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "bhowanipore-mallick-bari",
    "name": "Bhowanipore Mallick Bari",
    "slug": "bhowanipore-mallick-bari",
    "description": "A traditional Bonedi Bari puja in Bhawanipore, offering an intimate look at aristocratic family Durga Puja traditions.",
    "address": "Bhawanipore, Kolkata, West Bengal 700025",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.528,
    "longitude": 88.345,
    "image_url": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "chhatubabu-latubabur-bari",
    "name": "Chhatubabu Latubabur Bari",
    "slug": "chhatubabu-latubabur-bari",
    "description": "A famous Bonedi Bari puja near Beadon Street, known for its historic courtyard puja and music patronage.",
    "address": "Beadon Street, Kolkata, West Bengal 700006",
    "zone": "North Kolkata",
    "city": "Kolkata",
    "latitude": 22.584,
    "longitude": 88.366,
    "image_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "95-pally",
    "name": "95 Pally Durga Puja",
    "slug": "95-pally",
    "description": "A prominent community puja near Jodhpur Park area.",
    "address": "70A, Rahim Ostagar Road, Kolkata, West Bengal 700033",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.502,
    "longitude": 88.357,
    "image_url": "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "khidderpore-jubak-sangha",
    "name": "Khidderpore Jubak Sangha Club",
    "slug": "khidderpore-jubak-sangha",
    "description": "A well-known organization in the Kidderpore area hosting a popular and long-standing community Durga Puja.",
    "address": "Khidderpore, Kolkata, West Bengal 700023",
    "zone": "Howrah",
    "city": "Kolkata",
    "latitude": 22.535,
    "longitude": 88.322,
    "image_url": "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "santoshpur-avenue-south",
    "name": "Santoshpur Avenue South",
    "slug": "santoshpur-avenue-south",
    "description": "Often recognized for innovative, socially relevant themes depicting local life and street culture.",
    "address": "Santoshpur Avenue South, Santoshpur, Kolkata, West Bengal 700075",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.486,
    "longitude": 88.385,
    "image_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "kendua-shanti-sangha",
    "name": "Kendua Shanti Sangha",
    "slug": "kendua-shanti-sangha",
    "description": "A community puja in the Kendua area of Garia.",
    "address": "Kendua, Garia, Kolkata, West Bengal 700084",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.462,
    "longitude": 88.383,
    "image_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "behala-friends-club",
    "name": "Behala Friends Club",
    "slug": "behala-friends-club",
    "description": "A long-standing, traditional yet modern puja in Behala known for its vibrant atmosphere and larger-than-life idols.",
    "address": "Behala, Kolkata, West Bengal 700034",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.468,
    "longitude": 88.31,
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  },
  {
    "id": "ajeyo-sanghati",
    "name": "Ajeyo Sanghati (Haridevpur)",
    "slug": "ajeyo-sanghati",
    "description": "A prominent club in the Haridevpur circuit, known for its creative pandal work and festive spirit.",
    "address": "Haridevpur, Kolkata, West Bengal 700082",
    "zone": "South Kolkata",
    "city": "Kolkata",
    "latitude": 22.454,
    "longitude": 88.331,
    "image_url": "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
    "theme_year": "Durga Puja 2026 Masterwork"
  }
];

export const INITIAL_VISITS = [
  { userId: 'user_me', pandalId: 'bagbazar-sarbojanin', visitedAt: '2026-08-28T18:30:00Z' },
  { userId: 'user_me', pandalId: 'kumartuli-park', visitedAt: '2026-08-28T20:15:00Z' },
  { userId: 'user_me', pandalId: 'ahiritola-sarbojanin', visitedAt: '2026-08-29T17:45:00Z' },
  { userId: 'user_me', pandalId: 'college-square', visitedAt: '2026-08-29T21:10:00Z' },
  { userId: 'user_ananya', pandalId: 'bagbazar-sarbojanin', visitedAt: '2026-08-28T19:00:00Z' },
  { userId: 'user_ananya', pandalId: 'kumartuli-park', visitedAt: '2026-08-28T21:00:00Z' },
  { userId: 'user_ananya', pandalId: 'hatibagan-sarbojanin', visitedAt: '2026-08-29T18:00:00Z' },
  { userId: 'user_rahul', pandalId: 'bagbazar-sarbojanin', visitedAt: '2026-08-28T19:30:00Z' },
  { userId: 'user_rahul', pandalId: 'ahiritola-sarbojanin', visitedAt: '2026-08-29T18:30:00Z' },
  { userId: 'user_priya', pandalId: 'kumartuli-park', visitedAt: '2026-08-28T20:30:00Z' },
];

export const INITIAL_RATINGS: Rating[] = [
  {
    id: 'r_1',
    user_id: 'user_me',
    pandal_id: 'bagbazar-sarbojanin',
    rating: 5,
    scores: { overall: 5, theme: 5, idol: 5, lighting: 4, management: 4 },
    is_visible: true,
    review: 'Extraordinary clay craftsmanship and dignified atmosphere. The lighting accentuates every fine curve of the idol.',
    created_at: '2026-08-28T19:00:00Z',
    user: INITIAL_USER
  },
  {
    id: 'r_2',
    user_id: 'user_ananya',
    pandal_id: 'bagbazar-sarbojanin',
    rating: 5,
    scores: { overall: 5, theme: 5, idol: 5, lighting: 5, management: 4 },
    is_visible: true,
    review: 'Masterclass in theme execution. One of the top 3 pandals in Kolkata this year without question.',
    created_at: '2026-08-28T19:30:00Z',
    user: MOCK_FRIENDS[0]
  },
  {
    id: 'r_3',
    user_id: 'user_rahul',
    pandal_id: 'kumartuli-park',
    rating: 5,
    scores: { overall: 5, theme: 4, idol: 5, lighting: 5, management: 3 },
    is_visible: true,
    review: 'Unmatched scale and magnificent lighting. Highly recommended visiting late night to avoid peak queue.',
    created_at: '2026-08-28T21:30:00Z',
    user: MOCK_FRIENDS[1]
  }
];

export const INITIAL_ACTIVITIES: FriendActivity[] = [
  {
    id: 'act_1',
    type: 'visit',
    user: MOCK_FRIENDS[0],
    pandalName: 'Bagbazar Sarbojanin Durgotsab',
    pandalId: 'bagbazar-sarbojanin',
    timestamp: '15 mins ago'
  },
  {
    id: 'act_2',
    type: 'rating',
    user: MOCK_FRIENDS[1],
    pandalName: 'Kumartuli Park Durga Puja',
    pandalId: 'kumartuli-park',
    rating: 5,
    review: 'Grand architectural marvel. Absolutely spellbinding lighting display.',
    timestamp: '42 mins ago'
  }
];
